title: DockerLabs
description: Writeups de DockerLabs por Willy
theme: jekyll-theme-slate

author:
  nickname: Willy
  url: https://github.com/wilasky

markdown: kramdown
kramdown:
  input: GFM

header_pages:
  - index.md
  - writeups-dockerlabs/index.md
  - writeups-dockerlabs/machines/index.md
